apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-prod
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/edwindominicjoseph/idp-demo.git
    targetRevision: main
    path: gitops/environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # No automated sync — prod is manual-approval only (triggered by Jenkins)
