apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/boutique

namespace: staging

# Jenkins patches the newTag for the specific service that was built:
#   sed -i "/idp-demo-${SERVICE_NAME}/{n;s|newTag:.*|newTag: ${IMAGE_TAG}|}" \
#     gitops/environments/staging/kustomization.yaml
images:
- name: ghcr.io/edwindominicjoseph/idp-demo-boutique
  newTag: sha-latest
- name: ghcr.io/edwindominicjoseph/idp-demo-adservice
  newTag: sha-latest
- name: ghcr.io/edwindominicjoseph/idp-demo-cartservice
  newTag: sha-1a83579
- name: ghcr.io/edwindominicjoseph/idp-demo-checkoutservice
  newTag: sha-latest
- name: ghcr.io/edwindominicjoseph/idp-demo-currencyservice
  newTag: sha-ff284d3
- name: ghcr.io/edwindominicjoseph/idp-demo-emailservice
  newTag: sha-ed51510
- name: ghcr.io/edwindominicjoseph/idp-demo-loadgenerator
  newTag: sha-0279a30
- name: ghcr.io/edwindominicjoseph/idp-demo-paymentservice
  newTag: sha-13590ef
- name: ghcr.io/edwindominicjoseph/idp-demo-productcatalogservice
  newTag: sha-latest
- name: ghcr.io/edwindominicjoseph/idp-demo-recommendationservice
  newTag: sha-42fe850
- name: ghcr.io/edwindominicjoseph/idp-demo-shippingservice
  newTag: sha-a37f186
