apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/boutique

namespace: prod

# Jenkins patches the newTag for the specific service that was built:
#   sed -i "/idp-demo-${SERVICE_NAME}/{n;s|newTag:.*|newTag: ${IMAGE_TAG}|}" \
#     gitops/environments/prod/kustomization.yaml
images:
- name: ghcr.io/edwindominicjoseph/idp-demo-boutique
  newTag: 
- name: ghcr.io/edwindominicjoseph/idp-demo-adservice
  newTag: 
- name: ghcr.io/edwindominicjoseph/idp-demo-cartservice
  newTag: 
- name: ghcr.io/edwindominicjoseph/idp-demo-checkoutservice
  newTag: 
- name: ghcr.io/edwindominicjoseph/idp-demo-currencyservice
  newTag: 
- name: ghcr.io/edwindominicjoseph/idp-demo-emailservice
  newTag: 
- name: ghcr.io/edwindominicjoseph/idp-demo-loadgenerator
  newTag: 
- name: ghcr.io/edwindominicjoseph/idp-demo-paymentservice
  newTag: sha-d86ec95
- name: ghcr.io/edwindominicjoseph/idp-demo-productcatalogservice
  newTag: 
- name: ghcr.io/edwindominicjoseph/idp-demo-recommendationservice
  newTag: 
- name: ghcr.io/edwindominicjoseph/idp-demo-shippingservice
  newTag: 
